//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime WarrantyExpiration { get; set; }
        public Nullable<int> AssignedTo { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
