//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int InvoiceID { get; set; }
        public string InvoiceNumber { get; set; }
        public int ClientID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public double Amount { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
