//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCompanyEntities : DbContext
    {
        public ITCompanyEntities()
            : base("name=ITCompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<Leaves> Leaves { get; set; }
        public virtual DbSet<PerformanceReviews> PerformanceReviews { get; set; }
        public virtual DbSet<ProjectBudget> ProjectBudget { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Salaries> Salaries { get; set; }
        public virtual DbSet<Software> Software { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskAssignments> TaskAssignments { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Timesheets> Timesheets { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
    }
}
