//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReviews
    {
        public int ReviewID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int Score { get; set; }
        public string Comments { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
