//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBudget
    {
        public int BudgetID { get; set; }
        public int ProjectID { get; set; }
        public double AllocatedBudget { get; set; }
        public double SpentAmount { get; set; }
        public double RemainingBudget { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
