//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int SalaryID { get; set; }
        public int EmployeeID { get; set; }
        public double Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
