//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int SoftwareID { get; set; }
        public string SoftwareName { get; set; }
        public string LicenseKey { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int AssignedTo { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
