//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignments
    {
        public int TaskAssignmentID { get; set; }
        public int TaskID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AssigbedDate { get; set; }
        public Nullable<int> HoursWorked { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
